adminUser:
  password: vault:pr-126-2abc/adminUser:password
  username: admin
dashboardAuthID: vault:pr-126-2abc:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:pr-126-2abc:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-126-2abc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:pr-126-2abc/prow:hmacToken
segmentWriteKey: vault:pr-126-2abc:segmentWriteKey
